### ISSUE TITLE
Starting with BLE for Flutter

### ISSUE THREAD

**Issue by yudhiApp** [0015/IdeasNProjects#1]
Hi Eric,
Thanks your videos on youtube on BLE for Flutter. I am trying to build an app to receive text data from  a BLE device that uses transparent UART. Please can you tell me which one of your flutter projects is similar/ I can use as a template. I am new to development and BLE and finding it hard to implement.
Thank you,

Yudhi.

**Comment by 0015** [comment]
@yudhiApp All my projects so far are focusing on the BLE only. However, Transparent UART (BM70/RN4870) also supports BLE. You can figure out how to communicate them based on the example then change my project for yours. It's not gonna be too tough.
