### ISSUE TITLE
IdeasNprojects

### ISSUE THREAD

**Issue by StuartIanNaylor** [0015/IdeasNProjects#15]
Hi wondered if you might think this would be a worthy project.

https://invensense.tdk.com/wp-content/uploads/2015/02/Microphone-Array-Beamforming.pdf
https://www.analog.com/media/en/technical-documentation/application-notes/AN-1328.pdf

The above are analogue application but was thinking digitally if we could split a stereo I2S stream take one channel delay invert and then down mix the x2 channel streams then if we get the delay equal to mic distance we have a digital equivalent?

Being a C noob I am still looking blankly at the ESP ADF wondering how to split steams, but thought I would mention it to someone who is vastly more knowledgeable like yourself :)

**Comment by 0015** [comment]
@StuartIanNaylor I don't really understand this either. Haha. I'm sorry I couldn't help you. I always answer the comments in my project video. If it's not a code problem, please ask your question below the related video. Thank you.
