### ISSUE TITLE
Keyboard Input Question

### ISSUE THREAD

**Issue by tonyc770** [0015/IdeasNProjects#16]
Hi, thanks for the example!

I'm using the ESP32 with ILI9488 display like your application.
I just wanted to have a simple screen in landscape mode with a keyboard and a test area to enter in some data and then have that data stored.

I tried to modify your code to strip out items I don't need, but ran into issues.
Do you think you could demonstrate a simple example with keyboard and text area?

Thanks...

**Comment by 0015** [comment]
@tonyc770 I always answer the comments in my project video. If it's not a code problem, please ask your question below the related video. I'm thinking about doing a project regarding keyboard input, but I have a lot of projects to do first. I'll do it if I get a chance. Thank you for your understanding.
