### ISSUE TITLE
Cannot discover the ESP32 via BT

### ISSUE THREAD

**Issue by lunard** [0015/IdeasNProjects#18]
Hello to all!
I’m trying to use this really nice project as base for a social project, but I have a problem: on my Android 10 device, flutter_blue is not able to discover the ESP32.
The smartphone is able to discover the ESP32 via BT settings, but not with flutter_blue (the library discovers well other BT devices)
Someone has any suggestions ?
Thanks !!

**Comment by 0015** [comment]
Add permissions for Bluetooth 
We need to add the permission to use Bluetooth and access location:

Android
In the android/app/src/main/AndroidManifest.xml let’s add:

	 <uses-permission android:name="android.permission.BLUETOOTH" />  
	 <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />  
	 <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>

**Comment by 0015** [comment]
@lunard That's weird. It seems like the BT function of ESP32 doesn't seem to work properly. Can your ESP32 be seen in other BLE scanner apps? And could you please ask questions in the comments of the video of the project? That way, I can reply faster than here.
