### ISSUE TITLE
ESP32_CAM_Dashcam_FLUTTER, Android WIFI NAME: NULL

### ISSUE THREAD

**Issue by ceserik** [0015/IdeasNProjects#6]
Hi, i just managed to get the app and esp32 working. When i connect to any wifi I get WIFI NAME: NULL. It does this when I connect to ESP32-THAT-PROJECT and also for every wifi network. I cannot get to the video stream.
I am using Redmi Note 7, It may be an easy fix, because I have very little experience with this.

![Screenshot_2020-03-15-18-43-13-991_com thatproject flutter_dashcam_clone_app](https://user-images.githubusercontent.com/33375779/76707278-09bf4100-66ee-11ea-9ead-b7db623a1b86.jpg)

**Comment by ceserik** [comment]
Found a hotfix ! , but that sure isn't the proper way of fixing it, but i get to the video stream now
![image](https://user-images.githubusercontent.com/33375779/76707773-73414e80-66f2-11ea-89a1-a7a25fb89c3b.png)

**Comment by justoke** [comment]
If you check the code for where isTargetSSID is actually set, it seems from your screenshot that WiFi name is set to NULL - is the WiFi access point perhaps hidden? In any event if isTargetSSID is false then by swapping the logic as you have done would force it to connect, even though the WiFi name is not set.

in main.dart...
`isTargetSSID = targetSSID == wifiName;`

wifiName is set from the Connectivity class _connectivity instance, and it seems that this does not find the access point. It seems your phone has dual band WiFi, so it should work. You could try another device just to verify.
