### ISSUE TITLE
Send to Local Server Shifted Data

### ISSUE THREAD

**Issue by savasturk** [0015/IdeasNProjects#7]
Have a nice day, I want to send from ESP32 Cam module to local server shifted data and then apply reverse shift in local server. How can I do this operation? 
Thank you.

**Comment by savasturk** [comment]
@0015 Could you help me please?

**Comment by justoke** [comment]
Please could you try to explain in a bit more detail. I'll help you if I can.

**Comment by savasturk** [comment]
Thank you, I want to send fb->buf in this function client.sendBinary((const char*) fb->buf, fb->len); 
in ESP32_CAM_LocalServer/CameraWeb/CameraWeb.ino
 with left shifted
 and then
 I want to right shift in 
/ESP32_CAM_LocalServer/NodeServer/server.js / 
and render in web browser.

**Comment by 0015** [comment]
@savasturk Sorry, I didn't understand exactly what you wanted.
So, an image from ESP32CAM to the local server, and then It goes to ESP32CAM again???
