### ISSUE TITLE
I can change the cloudfunction temp field with postman but I can't change the firestore field with esp8266

### ISSUE THREAD

**Issue by sersaday** [0015/IdeasNProjects#8]
#include "ESP8266HTTPClient.h"
#include "ESP8266WiFi.h"
#include "DHTesp.h"
#include <ArduinoJson.h>

const char* ssid = "**********";
const char* password ="************";

const int iled = 12;                                            //drive the led of sensor
                                         
float temperature;
float humidity;
DHTesp dht;

void setup() {
  // put your setup code here, to run once:
  pinMode(iled, OUTPUT);
  digitalWrite(iled, LOW);                                     //iled default closed
  dht.setup(2, DHTesp::DHT11);
  Serial.begin(115200);                                         //send and receive at 115200 baud

  WiFi.begin(ssid, password);
  while(WiFi.status() != WL_CONNECTED){
    delay(500);
    Serial.print("Connected to this Wifi with IP: ");
    Serial.println(WiFi.localIP());
  }

}

void UpdateDHTSensorValue(){
   digitalWrite(iled, HIGH);
  delayMicroseconds(280);
  humidity = dht.getHumidity();
  temperature = dht.getTemperature();
  digitalWrite(iled, LOW);
  
  
  
  Serial.print("The current temp/hum concentration is: ");
  Serial.print(temperature);
  Serial.print("Derece");
  Serial.print(humidity);
  Serial.print("% nem");
   
}

void loop() {
  // put your main code here, to run repeatedly:
  if(WiFi.status() == WL_CONNECTED){
    UpdateDHTSensorValue();
    HTTPClient http;
    http.begin("https://**************.firebaseapp.com/api/v1/sensor/AKS96LT2ENs9R3MFHWR0");
    http.addHeader("Content-Type", "application/json");
    
    StaticJsonDocument<20> tempDocument;
    tempDocument["temp"] = temperature ;
    char buffer[20];
    serializeJson(tempDocument, buffer);
    http.PATCH(buffer);
    http.end();
    
    
  }else{
    Serial.println("Check your wifi connection");
  }

  delay(2000);

}

**Comment by 0015** [comment]
@sersaday Could you tell me what kind of error has occurred? Console log?
