### ISSUE TITLE
No image shows up at <my-IP-address>:8000/client

### ISSUE THREAD

**Issue by soluna1** [0015/IdeasNProjects#9]
Hi, 

thanks for the project, it is really fantastic! Unfortunately, after following all the steps the shell shows the "connected" message, but nothing shows up in the IP:8000/client. I've checked both server.js and client.html, and they seem fine. See below.
Inspecting the html at the browser this appears:
<img width="933" alt="image" src="https://user-images.githubusercontent.com/16171059/82831917-00a2db00-9eba-11ea-8b6e-88d8a268888b.png">

Could be something related to my router? Any idea?
It is the first time I try to do this connection, so I'm a bit lost.

thanks a lot for your help!

Sisi

`const path = require('path');
const express = require('express');
const WebSocket = require('ws');
const app = express();

const WS_PORT = 8888;
const HTTP_PORT = 8000;

const wsServer = new WebSocket.Server({port: WS_PORT}, () => console.log(`WS Server is listening at ${WS_PORT}`));

let connectedClients = [];
wsServer.on('connection', (ws, req)=>{
	console.log('Connected');
	connectedClients.push(ws);
	
	ws.on('message', data =>{
		connectedClients.forEach((ws,i) =>{
			if(ws.readyState === ws.OPEN){
				ws.send(data);
			}else{
				connectedClients.splice(i, 1);
			}
		})
	
	});

});

app.get('/client',(req,res)=>res.sendFile(path.resolve(__dirname, './client.html')));
app.listen(HTTP_PORT, ()=> console.log(`HTTP server listening at ${HTTP_PORT}`));

`

`<html>
    <head>
        <title>Client camera</title>
    </head>
    <body>
        <img src="">
        <script>
            const img = document.querySelector('img');
            const WS_URL = 'ws:///192.168.1.40:8888';
            const ws = WebSocket(WS_URL);
            let urlObject;
            ws.onopen = () => console.log(`Connected to ${WS_URL}`);
            ws.onmessage = message => {
                const arrayBuffer = message.data;
                if(urlObject){
                    URL.revokeObjectURL(urlObject);
                }
                urlObject = URL.createObjectURL(new Blob([arrayBuffer]));
                img.src = urlObject;
            }
        </script>
    </body>
</html>`

**Comment by 0015** [comment]
@soluna1 Are you sure you have a websocket module in your environment? Please install all npm modules for this project and try it again. https://www.npmjs.com/package/ws

**Comment by soluna1** [comment]
thanks, finally it works! I dunno what was really the issue, just wait a bit an the image come. 
Now going to tackle part 2, I want to access from outside my home, but I'm not sure about using google cloud services. Thanks for the project!
